### ISSUE TITLE
Visualization of the Rosenbrock Function

### ISSUE THREAD

**Issue by Daniel1402** [Daniel1402/GeneticAlgorithms.jl#9]
Create a plot that shows the Rosenbrock function with contour lines. The plotting function should also be able to visualize points passed as input parameters.

**Comment by DesjardinsRepos** [comment]
bin [hier](https://github.com/DesjardinsRepos/GeneticAlgorithms/commit/aff0c1990d3536eaa86289485b1f90afade796b9) gerade stuck mit den folgenden problemen:
- bei der visualisierung sind x und y vertauscht, keine ahnung ob das so soll
- die tests bekomm ich nicht ohne import fehler in die test_utils

**Comment by DesjardinsRepos** [comment]
Solved in #21
